package animaland;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Equipo 2 POO
 */
public class VAnimal extends javax.swing.JFrame {
     Animal animal;
   
     
    public VAnimal(String archivo, int id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         cargaImagenL(archivo);
         cargaFondo();
         animal=new Animal();
         this.id=id;
         lbNombre.setText(animal.getNombre(id));
          txAnimal.setText(animal.getInfo(id));
         this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    private int id;
    public void cargaFondo(){
        ImageIcon imagen; 
        imagen = new ImageIcon("./src/Imagenes/fondoA.jpg") ;
        Image imescala = imagen.getImage();
        imescala = imescala.getScaledInstance(lbFondo.getWidth() , lbFondo.getHeight(), Image.SCALE_DEFAULT);
        imagen = new ImageIcon(imescala);
        lbFondo.setIcon(imagen);
    }
    public void cargaImagenL(String archivo){
        ImageIcon imagen; 
        imagen = new ImageIcon("./src/Imagenes/"+archivo) ;
        Image imescala = imagen.getImage();
        imescala = imescala.getScaledInstance(lbImagen.getWidth() , lbImagen.getHeight(), Image.SCALE_DEFAULT);
        imagen = new ImageIcon(imescala);
        lbImagen.setIcon(imagen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbImagen = new javax.swing.JLabel();
        btSonido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txAnimal = new javax.swing.JEditorPane();
        lbNombre = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImagen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(lbImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 80, 380, 240));

        btSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sonido.jpg"))); // NOI18N
        btSonido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSonidoActionPerformed(evt);
            }
        });
        jPanel1.add(btSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 80, 50));

        txAnimal.setEditable(false);
        jScrollPane1.setViewportView(txAnimal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 360, 230));

        lbNombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbNombre.setText("Animal");
        jPanel1.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));
        jPanel1.add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 960, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSonidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSonidoActionPerformed
        animal.getSound(id);
    }//GEN-LAST:event_btSonidoActionPerformed

    
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
        getImage(ClassLoader.getSystemResource("Imagenes/AGUILA2.png"));
        return retValue;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new VLeon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSonido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbImagen;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JEditorPane txAnimal;
    // End of variables declaration//GEN-END:variables
}
